'use client';

import {useLocale,useTranslation} from './language';
import {numberLocale,translator,localizeEvidence,type Locale} from '@seo/shared/i18n';
import{useEffect,useRef,useState}from'react';import{useRouter}from'next/navigation';import{CircleAlert,Clock,LoaderCircle,Pause,Play}from'lucide-react';type C={status:string;processedPages:number;discoveredPages:number;pendingUrls:number;errorUrls:number;analyzedHtmlPages:number;redirectCount:number;skippedUrls?:number;statusMessage:string;error?:string|null;startedAt?:string|Date|null};
export function Progress({id,initial}:{id:string;initial:C}){const t=useTranslation(),locale=useLocale();const[c,setC]=useState(initial),[busy,setBusy]=useState(false),[requestError,setRequestError]=useState(''),router=useRouter(),samples=useRef<{t:number;n:number}[]>([]);useEffect(()=>{const now=Date.now(),s=samples.current;s.push({t:now,n:c.processedPages});while(s.length>2&&now-s[0].t>180000)s.shift()},[c.processedPages]);useEffect(()=>{if(['COMPLETED','PARTIAL'].includes(c.status)){router.replace(`/rapor/${id}`);return}if(c.status==='FAILED')return;let active=true;const controller=new AbortController();let timer:ReturnType<typeof setTimeout>;
const poll=async()=>{try{const r=await fetch(`/api/crawls/${id}`,{cache:'no-store',signal:controller.signal});if(!r.ok)throw new Error();const next=await r.json();if(active){setC(next);setRequestError('')}}catch{if(active)setRequestError(t('m369'))}finally{if(active)timer=setTimeout(poll,1500)}};
timer=setTimeout(poll,1500);return()=>{active=false;controller.abort();clearTimeout(timer)}},[c.status,id,router]);async function control(action:'pause'|'resume'){setBusy(true);setRequestError('');try{const r=await fetch(`/api/crawls/${id}/control`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action})});const data=await r.json();if(!r.ok)throw new Error(data.error??t('m373'));samples.current=[];setC(previous=>({...previous,...data}))}catch(error){setRequestError(error instanceof Error?t(error.message):t('m373'))}finally{setBusy(false)}}if(c.status==='FAILED')return <div className="critical rounded-xl p-5"><b className="flex gap-2"><CircleAlert/>{t("m017")}</b><p>{t(c.error??t("m326"))}</p></div>;const eta=c.status==='RUNNING'?estimate(c,samples.current,locale):null;return <div><div className="mb-4 flex items-center justify-between"><b className="flex gap-2 text-brand">{c.status==='PAUSED'?<Pause className="text-amber-600"/>:<LoaderCircle className="animate-spin text-action"/>}{c.status==='PAUSED'?t("m018"):t("m019")}</b><button className="btn py-2" disabled={busy||!['RUNNING','PAUSED'].includes(c.status)} onClick={()=>control(c.status==='PAUSED'?'resume':'pause')}>{c.status==='PAUSED'?<Play size={16}/>:<Pause size={16}/>} {c.status==='PAUSED'?t("m020"):t("m021")}</button></div><p className="text-sm">{t(c.statusMessage)}</p>{requestError&&<p role="alert" className="mt-2 text-sm text-red-700">{requestError}</p>}{eta&&<div className="mt-4 flex items-start gap-3 rounded-xl bg-blue-50 p-4 text-sm text-blue-900"><Clock className="mt-0.5 shrink-0" size={18}/><span><b className="block">{eta.title}</b>{eta.detail&&<small className="text-blue-800">{eta.detail}</small>}</span></div>}<div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-3"><Stat n={c.discoveredPages} l={t("m022")}/><Stat n={c.processedPages} l={t("m023")}/><Stat n={c.pendingUrls} l={t("m324")}/><Stat n={c.analyzedHtmlPages} l={t("m325")}/><Stat n={c.redirectCount} l={t("m024")}/><Stat n={c.errorUrls} l={t("m025")}/>{(c.skippedUrls??0)>0&&<Stat n={c.skippedUrls!} l={t("m026")}/>}</div></div>}
/** Son 3 dakikadaki hızı kullanır; yeterli ölçüm yoksa taramanın başından beri geçen süreye döner. */
function estimate(c:C,s:{t:number;n:number}[],locale:Locale){const t=translator(locale);if(c.pendingUrls===0)return c.processedPages>0?{title:t("m027"),detail:t("m028")}:null;let perSec=0;const a=s[0],b=s[s.length-1];if(a&&b&&b.t-a.t>=20000&&b.n>a.n)perSec=(b.n-a.n)/((b.t-a.t)/1000);else if(c.startedAt&&c.processedPages>0){const sec=(Date.now()-new Date(c.startedAt).getTime())/1000;if(sec>=20)perSec=c.processedPages/sec}if(!perSec)return{title:t("m029"),detail:t("m030")};const perMin=Math.round(perSec*60);return{title:t("m031", [duration(c.pendingUrls/perSec,locale)]),detail:t("m032", [perMin.toLocaleString(numberLocale(locale))])}}
function duration(sec:number,locale:Locale){const t=translator(locale);const min=Math.round(sec/60);if(min<1)return t("m327");if(min<60)return t("m033", [min]);const h=Math.floor(min/60),m=min%60;return t("m034", [h, m?t("m328", [m]):''])}
function Stat({n,l}:{n:number;l:string}){const locale=useLocale(),t=useTranslation();return <div className="rounded-xl bg-slate-50 p-4"><div className="text-2xl font-black text-brand">{n.toLocaleString(numberLocale(locale))}</div><div className="text-xs text-muted">{l}</div></div>}
