'use client';
import { useEffect, useState } from 'react';
import { numberLocale } from '@seo/shared/i18n';
import { useLocale, useTranslation } from './language';
type Schedule = { enabled: boolean; frequency?: string; nextRunAt?: string; lastRunAt?: string };
export function ScheduleControls({ host }: { host: string }) {
  const locale = useLocale(), t = useTranslation(), [schedule, setSchedule] = useState<Schedule | null>(null), [frequency, setFrequency] = useState('WEEKLY'), [busy, setBusy] = useState(false), [error, setError] = useState(false), [loading, setLoading] = useState(true);
  const endpoint = `/api/projects/${encodeURIComponent(host)}/schedule`;
  useEffect(() => { const c = new AbortController(); fetch(endpoint, { signal: c.signal }).then(async r => { if (!r.ok) throw new Error(); const s = await r.json(); setSchedule(s); if (s?.frequency) setFrequency(s.frequency); }).catch(() => { if (!c.signal.aborted) setError(true); }).finally(() => { if (!c.signal.aborted) setLoading(false); }); return () => c.abort(); }, [endpoint]);
  async function save(method: string) { setBusy(true); setError(false); try { const r = await fetch(endpoint, { method, headers: { 'Content-Type': 'application/json' }, ...(method === 'POST' ? { body: JSON.stringify({ frequency }) } : {}) }); if (!r.ok) throw new Error(); setSchedule(await r.json()); } catch { setError(true); } finally { setBusy(false); } }
  return <section className="card mt-8 p-6" aria-busy={busy || loading}><h2 className="text-lg font-bold text-brand">{t('saas.scheduledCrawls')}</h2><p className="mt-2 text-sm text-muted">{t('saas.scheduleIntro')}</p><div className="mt-4 flex flex-wrap items-end gap-3"><label className="flex flex-col gap-2 text-sm">{t('saas.frequency')}<select className="rounded-lg border p-2" value={frequency} onChange={e => setFrequency(e.target.value)}><option value="WEEKLY">{t('saas.weekly')}</option><option value="MONTHLY">{t('saas.monthly')}</option></select></label><button className="btn" disabled={busy || loading} onClick={() => save('POST')}>{t('saas.saveSchedule')}</button>{schedule?.enabled && <button className="btn" disabled={busy} onClick={() => save('DELETE')}>{t('saas.disableSchedule')}</button>}</div><p className="mt-3 text-sm" role="status">{error ? t('saas.error') : loading ? t('saas.loading') : schedule?.enabled ? `${t('saas.nextRun')}: ${new Date(schedule.nextRunAt!).toLocaleString(numberLocale(locale))}` : t('saas.scheduleDisabled')}</p>{schedule?.lastRunAt && <p className="mt-1 text-xs text-muted">{t('saas.lastCrawl')}: {new Date(schedule.lastRunAt).toLocaleString(numberLocale(locale))}</p>}</section>;
}
